# Generated by Django 3.1.4 on 2023-12-05 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carteira',
            fields=[
                ('id_carteira', models.AutoField(db_column='id_carteira', primary_key=True, serialize=False)),
                ('nome_carteira', models.CharField(max_length=255)),
                ('valor_total_carteira', models.FloatField()),
                ('descricao_carteira', models.TextField()),
                ('id_portfolio', models.ForeignKey(db_column='id_portfolio', on_delete=django.db.models.deletion.CASCADE, to='portfolio.portfolio')),
            ],
            options={
                'db_table': 'Carteira',
            },
        ),
    ]
