# Generated by Django 3.1.4 on 2023-12-05 05:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acao',
            fields=[
                ('id_acao', models.AutoField(db_column='id_acao', primary_key=True, serialize=False)),
                ('nome_acao', models.CharField(max_length=255)),
                ('preco_mais_baixo', models.FloatField()),
                ('preco_mais_alto', models.FloatField()),
                ('simbolo_acao', models.CharField(max_length=20)),
                ('nome_empresa', models.CharField(max_length=150)),
                ('data_acao', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'Acao',
            },
        ),
    ]
